// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isDemo } from '@/lib/demoMode';
import { demoClient } from './demoClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const realClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// En MODE DÉMO, on route les points d'entrée vers un client fictif local
// (aucun appel réseau vers la vraie base). Sinon, comportement inchangé.
// Les méthodes réelles sont appelées SUR realClient pour préserver `this`.
const wrapper = {
  from: (table: string) => (isDemo() ? demoClient.from(table) : realClient.from(table as any)),
  rpc: (fn: string, params?: any) => (isDemo() ? demoClient.rpc() : realClient.rpc(fn as any, params)),
  get functions() { return isDemo() ? demoClient.functions : realClient.functions; },
  get auth() { return isDemo() ? demoClient.auth : realClient.auth; },
  get storage() { return realClient.storage; },
  get realtime() { return realClient.realtime; },
  channel: (...args: any[]) => (isDemo() ? demoClient.channel() : (realClient as any).channel(...args)),
  removeChannel: (...args: any[]) => (isDemo() ? demoClient.removeChannel() : (realClient as any).removeChannel(...args)),
};

export const supabase = wrapper as unknown as typeof realClient;
